### ISSUE TITLE
module 'comtypes.gen.WeChatRobotCOMLib' has no attribute 'IRobotEvent'

### ISSUE THREAD

**Issue by CharlesLi114** [ljc545w/ComWeChatRobot#102]
在注册之后运行 com 中的demo，提示错误：
Traceback (most recent call last):
  File "D:/projects/P/AlphaCapture/other_apis/ComWeChatRobot-master-0830/ComWeChatRobot-master/Python/com/test.py", line 88, in <module>
    wx = WeChatRobot(pid_list[0])
  File "D:\projects\P\AlphaCapture\other_apis\ComWeChatRobot-master-0830\ComWeChatRobot-master\Python\com\wxRobot.py", line 145, in __init__
    self.robot = robot or _WeChatRobotClient.instance().robot
  File "D:\projects\P\AlphaCapture\other_apis\ComWeChatRobot-master-0830\ComWeChatRobot-master\Python\com\wxRobot.py", line 28, in instance
    cls._instance = cls()
  File "D:\projects\P\AlphaCapture\other_apis\ComWeChatRobot-master-0830\ComWeChatRobot-master\Python\com\wxRobot.py", line 33, in __init__
    self.event = comtypes.client.CreateObject("WeChatRobot.RobotEvent")
  File "D:\projects\P\AlphaCapture\wechatcapture\service\venv\lib\site-packages\comtypes\client\__init__.py", line 250, in CreateObject
    return _manage(obj, clsid, interface=interface)
  File "D:\projects\P\AlphaCapture\wechatcapture\service\venv\lib\site-packages\comtypes\client\__init__.py", line 188, in _manage
    obj = GetBestInterface(obj)
  File "D:\projects\P\AlphaCapture\wechatcapture\service\venv\lib\site-packages\comtypes\client\__init__.py", line 112, in GetBestInterface
    interface = getattr(mod, itf_name)
AttributeError: module 'comtypes.gen.WeChatRobotCOMLib' has no attribute 'IRobotEvent'

Wechat 3.7.0.30，python 版本 3.8
求大佬指导可能是什么问题？

**Comment by ljc545w** [comment]
如果以前使用过旧版本，需要先清理下comtypes.gen目录中的缓存。comtypes有时会有延迟。

**Comment by CharlesLi114** [comment]
用tag里面的zip + test 放在同级目录，somehow works。可能是延时？

**Comment by ljc545w** [comment]
有使用过老版本的com注册过没有，有的话，清理下python site-packages中的comtypes.gen目录。
