### ISSUE TITLE
是我哪里写的不对吗？ 使用新的com，好像启动不了服务

### ISSUE THREAD

**Issue by QiGuaiDeDiDi** [ljc545w/ComWeChatRobot#130]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [x] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [x] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈或建议
- [ ] 添加新的功能
- [x] 请求技术支持

robot = comtypes.client.CreateObject("WeChatRobot.CWeChatRobot")
robot.CStartRobotService(wx_pid)
在执行第二条语句的时候，报错了，提示【TypeError: call takes exactly 1 arguments (2 given)】
但是实际上我只传了一个微信PID进去。
在使用您的test.py脚本时，运行也出现了该错误错误提示如下：

------------
Traceback (most recent call last):
  File "C:/Python38/ComWeChatBot2.0/test.py", line 87, in <module>
    wx = WeChatRobot(pid_list[0])
  File "C:\Python38\ComWeChatBot2.0\wxRobot.py", line 142, in __init__
    self.robot = robot or _WeChatRobotClient.instance().robot
  File "C:\Python38\ComWeChatBot2.0\wxRobot.py", line 27, in instance
    cls._instance = cls()
  File "C:\Python38\ComWeChatBot2.0\wxRobot.py", line 33, in __init__
    self.com_pid = self.robot.CStopRobotService(0)
TypeError: call takes exactly 1 arguments (2 given)
------------

**Comment by ljc545w** [comment]
可能需要重新注册COM组件了
