### ISSUE TITLE
python调用ForwardMessage方法出现异常

### ISSUE THREAD

**Issue by chenkaimeng** [ljc545w/ComWeChatRobot#144]
使用python接口，调用ForwardMessage方法出现如下异常，SendImage与SendText方法均正常，已更新至最新版本3.7.0.30-0.0.8

Traceback (most recent call last):
  File "D:\Program Files\Python310\lib\site-packages\comtypes\__init__.py", line 274, in __getattr__
    fixed_name = self.__map_case__[name.lower()]
KeyError: 'cforwardmessage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\auto-workspace\speedup-robot\run.py", line 42, in <module>
    wxServer.startWxServer()
  File "D:\auto-workspace\speedup-robot\group_msg_robot\dll_robot\server.py", line 23, in startWxServer
    consumer.start()
  File "D:\auto-workspace\speedup-robot\group_msg_robot\dll_robot\consumer.py", line 36, in start
    self.taskHandlers[task.taskType].process(task)
  File "D:\auto-workspace\speedup-robot\group_msg_robot\dll_robot\task_handler.py", line 82, in process
    wx.ForwardMessage(wxid=group.get('wxid'), msgid=msg.get('msgid'))
  File "D:\auto-workspace\speedup-robot\group_msg_robot\dll_robot\robot_api.py", line 1067, in ForwardMessage
    return self.robot.CForwardMessage(self.pid,wxid,msgid)
  File "D:\Program Files\Python310\lib\site-packages\comtypes\__init__.py", line 276, in __getattr__
    raise AttributeError(name)
AttributeError: CForwardMessage

**Comment by ljc545w** [comment]
换版本的话，要先执行一遍CWeChatRobot.exe unregserver，然后找到comtypes包下的gen目录，删除里面的缓存文件，再重新注册即可。

**Comment by chenkaimeng** [comment]
> 

明白了，我应该就是没有删除comtypes缓存的问题，非常感谢。
