### ISSUE TITLE
python测试代码运行错误，显示参数错误

### ISSUE THREAD

**Issue by liuluyang** [ljc545w/ComWeChatRobot#183]
**我确定我已经查看了** (标注`[ ]`为`[x]`)

- [ ] [README](https://github.com/ljc545w/ComWeChatRobot/blob/master/README.md)
- [ ] [其他 Issues](https://github.com/ljc545w/ComWeChatRobot/issues)

----

**我要申请**  (标注`[ ]`为`[x]`)

- [ ] BUG 反馈或建议
- [ ] 添加新的功能
- [ ] 请求技术支持

**Comment by liuluyang** [comment]
Traceback (most recent call last):
  File "E:/Downloads/ComWeChatRobot-3.7.0.30-0.1.1-pre/Python/com/test.py", line 94, in <module>
    show_interfaces()
  File "E:/Downloads/ComWeChatRobot-3.7.0.30-0.1.1-pre/Python/com/test.py", line 79, in show_interfaces
    robot = wxRobot.WeChatRobot(0).robot
  File "E:\Downloads\ComWeChatRobot-3.7.0.30-0.1.1-pre\Python\com\wxRobot.py", line 144, in __init__
    self.robot = robot or _WeChatRobotClient.instance().robot
  File "E:\Downloads\ComWeChatRobot-3.7.0.30-0.1.1-pre\Python\com\wxRobot.py", line 29, in instance
    cls._instance = cls()
  File "E:\Downloads\ComWeChatRobot-3.7.0.30-0.1.1-pre\Python\com\wxRobot.py", line 35, in __init__
    self.com_pid = self.robot.CStopRobotService(0)
TypeError: call takes exactly 1 arguments (2 given)

这是错误信息，麻烦帮忙看一下，显示参数错误
